### ISSUE TITLE
Publish to AppSource

### ISSUE THREAD

**Issue by sgratzl** [upsetjs/upsetjs_powerbi_visuals#2]
https://docs.microsoft.com/en-us/power-bi/developer/visuals/office-store

- [x] request app package xml
- [x] register at partner center
- [ ] create addon https://docs.microsoft.com/en-us/power-bi/developer/visuals/office-store#submitting-to-partner-center
- [ ] track status https://docs.microsoft.com/en-us/power-bi/developer/visuals/office-store#tracking-submission-status-and-usage

https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-certified

- [ ] create submission branch https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-certified#code-repository-requirements
- [ ] ensure requirements
- [ ] submit https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-certified#submitting-a-power-bi-visual-for-certification

**Comment by yscumc** [comment]
Looking forward to this being certified! :)
